# zentao 8.2.5
#
# VERSION              1.0

FROM centos:centos7

MAINTAINER hoperuin<wf1337@gmail.com>

ADD http://dl.cnezsoft.com/zentao/8.2.5/ZenTaoPMS.8.2.5.zbox_64.tar.gz /opt

EXPOSE 80 3306

ENTRYPOINT ["bash", "/opt/zbox/zbox start"]